const ExportService = {
    async generateReport(userId, journalType, logs) {
        try {
            const user = AuthService.getCurrentUser();
            const achievements = await AchievementService.getUserAchievements(userId);
            const totalPoints = await AchievementService.getUserPoints(userId);
            
            const reportData = {
                user: user.name,
                journalType: this.getJournalTypeName(journalType),
                generatedAt: new Date().toISOString(),
                totalDays: logs.length,
                totalPoints,
                achievements: achievements.length,
                logs,
                achievementsList: achievements
            };

            return this.createPDFContent(reportData);
        } catch (error) {
            console.error('Failed to generate report:', error);
            throw error;
        }
    },

    getJournalTypeName(type) {
        const names = {
            'sports_journal': 'Sports Social Journey',
            'highlight_emotion': 'Highlight Moments Journey', 
            'career_journal': 'Career Flow Journey',
            'sleep_journal': 'Dream Dialogue Journey'
        };
        return names[type] || 'Flow Journey';
    },

    createPDFContent(data) {
        const content = `
# ${data.journalType} - 21-Day Report

**Participant:** ${data.user}
**Generated:** ${new Date(data.generatedAt).toLocaleDateString()}
**Total Days Completed:** ${data.totalDays}/21
**Achievements Earned:** ${data.achievements}
**Total Points:** ${data.totalPoints}

## Journey Overview
You've completed ${data.totalDays} days of your ${data.journalType}. This represents your dedication to personal growth and self-improvement.

## Achievements Unlocked
${data.achievementsList.map(achievement => 
    `🏆 **${achievement.name}** (${achievement.points} points)\n   ${achievement.description}`
).join('\n\n')}

## Daily Progress Summary
${data.logs.slice(0, 10).map(log => 
    `**Day ${log.day}** - ${new Date(log.timestamp).toLocaleDateString()}\n` +
    `Ratings: ${this.getLogRatings(log)}\n` +
    `Entry: ${(log.content || log.emotion || log.strengths || log.dreamEntry || '').slice(0, 100)}...`
).join('\n\n')}

## Growth Insights
Based on your 21-day journey, you've shown remarkable commitment to personal development. Your consistent journaling has contributed to building stronger self-awareness and emotional intelligence.

---
*Generated by JEC Flow Platform - Finding your rhythm.*
        `;
        
        return content;
    },

    getLogRatings(log) {
        const ratings = [];
        if (log.moodRating) ratings.push(`Mood: ${log.moodRating}/10`);
        if (log.energyLevel) ratings.push(`Energy: ${log.energyLevel}/10`);
        if (log.skillRating) ratings.push(`Skills: ${log.skillRating}/10`);
        if (log.progressRating) ratings.push(`Progress: ${log.progressRating}/10`);
        if (log.sleepQuality) ratings.push(`Sleep: ${log.sleepQuality}/10`);
        if (log.sleepDuration) ratings.push(`Duration: ${log.sleepDuration}h`);
        return ratings.join(', ') || 'No ratings';
    },

    downloadAsText(content, filename) {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
};